services:
  web:
    image: app-name:latest
    build:
      target: web
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "5173:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - .:/app:delegated
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    privileged: true


  db:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Zaq12wsx
      MYSQL_DATABASE: ipz
      MYSQL_USER: root
      MYSQL_PASSWORD: Zaq12wsx
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: Zaq12wsx
    ports:
      - "6969:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
