name: Run PHPUnit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, intl, xml, zip, pdo_mysql

      - name: Install dependencies
        run: composer install

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Update .env with database configuration
        run: |
          sed -i 's/DB_HOST=db/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_DATABASE=ipz/DB_DATABASE=test_db/' .env
          sed -i 's/DB_USERNAME=root/DB_USERNAME=root/' .env
          sed -i 's/DB_PASSWORD=Zaq12wsx/DB_PASSWORD=root/' .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run database migrations
        run: php artisan migrate

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit ./tests/
