name: Weekly Dependency Updates

on:
  schedule:
    # Run at midnight (00:00) every Sunday
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Update Composer dependencies
        id: composer-update
        run: |
          if [ -f composer.json ]; then
            echo "Updating Composer dependencies..."
            composer update --no-interaction --no-progress
            if git diff --name-only | grep -q "composer.lock"; then
              echo "composer_changes=true" >> $GITHUB_OUTPUT
            else
              echo "No Composer dependencies to update"
              echo "composer_changes=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "No composer.json found, skipping Composer updates"
            echo "composer_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Update Bun dependencies
        id: bun-update
        run: |
          if [ -f package.json ]; then
            echo "Updating Bun dependencies..."
            bun update
            if git diff --name-only | grep -q "bun.lockb\|package-lock.json"; then
              echo "bun_changes=true" >> $GITHUB_OUTPUT
            else
              echo "No Bun dependencies to update"
              echo "bun_changes=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "No package.json found, skipping Bun updates"
            echo "bun_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        if: steps.composer-update.outputs.composer_changes == 'true' || steps.bun-update.outputs.bun_changes == 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies [automated]"
          title: "Weekly Dependencies Update"
          body: |
            This is an automated weekly dependencies update.

            Changes:
            ${{ steps.composer-update.outputs.composer_changes == 'true' && '- Updated Composer dependencies' || '' }}
            ${{ steps.bun-update.outputs.bun_changes == 'true' && '- Updated Bun dependencies' || '' }}
          branch: deps/weekly-update-${{ github.run_number }}
          base: ${{ github.ref }}
          delete-branch: true
