name: Weekly Dependency Updates

on:
  schedule:
    # Run at midnight (00:00) every Sunday
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Update Composer dependencies
        id: composer-update
        run: |
          if [ -f composer.json ]; then
            echo "Updating Composer dependencies..."
            composer update --no-interaction --no-progress
            if git diff --name-only | grep -q "composer.lock"; then
              echo "composer_changes=true" >> $GITHUB_OUTPUT
            else
              echo "No Composer dependencies to update"
              echo "composer_changes=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "No composer.json found, skipping Composer updates"
            echo "composer_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Update Bun dependencies
        id: bun-update
        run: |
          if [ -f package.json ]; then
            echo "Updating Bun dependencies..."
            bun update
            if git diff --name-only | grep -q "bun.lockb\|package-lock.json"; then
              echo "bun_changes=true" >> $GITHUB_OUTPUT
            else
              echo "No Bun dependencies to update"
              echo "bun_changes=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "No package.json found, skipping Bun updates"
            echo "bun_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create Pull Request
        if: steps.composer-update.outputs.composer_changes == 'true' || steps.bun-update.outputs.bun_changes == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="deps/weekly-update-$(date +%Y-%m-%d)"
          git checkout -b $BRANCH_NAME
          
          git add .
          git commit -m "chore: update dependencies [automated]"
          
          git push --set-upstream origin $BRANCH_NAME
          
          # Create PR using GitHub CLI
          gh pr create \
            --title "Weekly Dependencies Update" \
            --body "This is an automated weekly dependencies update.
            
            Changes:
            ${{ steps.composer-update.outputs.composer_changes == 'true' && '- Updated Composer dependencies' || '' }}
            ${{ steps.bun-update.outputs.bun_changes == 'true' && '- Updated Bun dependencies' || '' }}" \
            --base main
